/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package statsproject;

/** class that holds main method*/
public class App {

    public static void main(String[] args) {
        InputManager eventInput = new InputManager();
    }
}
